//! Shell history with crash-safe append-only log, fuzzy search, and automatic backups.
//!
//! # Design
//!
//! This module uses an append-only log for durability combined with an in-memory
//! index for fast fuzzy search. The key invariant is that we NEVER lose executed
//! commands - when a command is executed, it's immediately written to disk and
//! fsynced before the shell continues.
//!
//! ## Log Format
//!
//! The log is a newline-delimited JSON file where each line is an event:
//! - `exec` events record a new command execution
//! - `amend` events update metadata on a previously recorded command
//!
//! This allows us to record commands immediately on execution, then update
//! with exit codes, duration, etc. when the command completes.
//!
//! ## Concurrency
//!
//! The ShellHistory is designed to be wrapped in `Arc` and shared across
//! multiple shell panes. File-level locking ensures safe concurrent writes.
//!
//! ## Backups
//!
//! Backups are created at exponentially increasing intervals (1h, 2h, 4h, 8h, etc.)
//! to protect against corruption while not using too much disk space.

use fs2::FileExt;
use fuzzy_matcher::skim::SkimMatcherV2;
use fuzzy_matcher::FuzzyMatcher;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs::{self, File, OpenOptions};
use std::io::{self, BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::sync::{Mutex, RwLock};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use uuid::Uuid;

/// Unique identifier for a history entry
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EntryId(String);

impl EntryId {
    pub fn new() -> Self {
        EntryId(Uuid::new_v4().to_string())
    }

    pub fn from_string(s: String) -> Self {
        EntryId(s)
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for EntryId {
    fn default() -> Self {
        Self::new()
    }
}

/// Source of the command - was it typed by a human or generated by AI?
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CommandSource {
    Human,
    Ai,
}

impl Default for CommandSource {
    fn default() -> Self {
        CommandSource::Human
    }
}

/// A history entry representing an executed command
#[derive(Debug, Clone)]
pub struct HistoryEntry {
    pub id: EntryId,
    pub command: String,
    pub executed_at: SystemTime,
    pub exit_code: Option<i32>,
    pub source: CommandSource,
    pub killed: bool,
    pub duration_ms: Option<u64>,
    /// Working directory when command was executed
    pub cwd: Option<String>,
}

impl HistoryEntry {
    pub fn new(command: String, source: CommandSource) -> Self {
        HistoryEntry {
            id: EntryId::new(),
            command,
            executed_at: SystemTime::now(),
            exit_code: None,
            source,
            killed: false,
            duration_ms: None,
            cwd: None,
        }
    }

    pub fn with_cwd(mut self, cwd: String) -> Self {
        self.cwd = Some(cwd);
        self
    }
}

/// Events that can be written to the append-only log
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
enum LogEvent {
    /// A new command was executed
    Exec {
        id: String,
        cmd: String,
        #[serde(rename = "time")]
        timestamp: u64,
        source: CommandSource,
        #[serde(skip_serializing_if = "Option::is_none")]
        cwd: Option<String>,
    },
    /// Amend an existing entry with completion information
    Amend {
        id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        exit_code: Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        duration_ms: Option<u64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        killed: Option<bool>,
    },
    /// Import from external history (zsh/bash)
    Import {
        id: String,
        cmd: String,
        #[serde(rename = "time")]
        timestamp: u64,
        #[serde(skip_serializing_if = "Option::is_none")]
        original_format: Option<String>,
    },
}

/// Search result from fuzzy matching
#[derive(Debug, Clone)]
pub struct SearchResult {
    pub entry: HistoryEntry,
    pub score: i64,
}

/// Breakdown of the scoring components for a search result
#[derive(Debug, Clone, Default)]
pub struct ScoreBreakdown {
    /// Score from the fuzzy matcher (normalized)
    pub match_score: i64,
    /// Bonus for match density (matched chars / command length)
    pub density_bonus: i64,
    /// Bonus for successful exit code (0)
    pub exit_code_bonus: i64,
    /// Bonus based on how many times this command has been run
    pub frequency_bonus: i64,
    /// Bonus based on how recently the command was last run
    pub recency_bonus: i64,
}

impl ScoreBreakdown {
    /// Calculate the total score from all components
    pub fn total(&self) -> i64 {
        self.match_score
            + self.density_bonus
            + self.exit_code_bonus
            + self.frequency_bonus
            + self.recency_bonus
    }
}

/// Search result with match indices for highlighting
#[derive(Debug, Clone)]
pub struct HistorySearchResult {
    pub entry: HistoryEntry,
    /// Total computed score (for sorting)
    pub score: i64,
    /// Breakdown of individual score components
    pub score_breakdown: ScoreBreakdown,
    /// Character indices that matched the query (for highlighting)
    pub match_indices: Vec<usize>,
}

/// Backup interval configuration
#[derive(Debug, Clone)]
pub struct BackupConfig {
    /// Base intervals for backups (in seconds)
    /// Default: 1h, 2h, 4h, 8h, 16h, 1d, 2d, 4d, 1w, 2w, 1mo
    pub intervals: Vec<Duration>,
}

impl Default for BackupConfig {
    fn default() -> Self {
        BackupConfig {
            intervals: vec![
                Duration::from_secs(3600),    // 1 hour
                Duration::from_secs(7200),    // 2 hours
                Duration::from_secs(14400),   // 4 hours
                Duration::from_secs(28800),   // 8 hours
                Duration::from_secs(57600),   // 16 hours
                Duration::from_secs(86400),   // 1 day
                Duration::from_secs(172800),  // 2 days
                Duration::from_secs(345600),  // 4 days
                Duration::from_secs(604800),  // 1 week
                Duration::from_secs(1209600), // 2 weeks
                Duration::from_secs(2592000), // ~1 month
            ],
        }
    }
}

/// Shell history manager
///
/// This is designed to be wrapped in `Arc` for concurrent access from
/// multiple shell panes.
pub struct ShellHistory {
    /// In-memory entries indexed by ID
    entries: RwLock<HashMap<EntryId, HistoryEntry>>,

    /// Ordered list of entry IDs (most recent last)
    entry_order: RwLock<Vec<EntryId>>,

    /// Path to the history log file
    log_path: PathBuf,

    /// Lock for serializing writes
    write_lock: Mutex<()>,

    /// Fuzzy matcher for search
    matcher: SkimMatcherV2,

    /// Backup configuration
    backup_config: BackupConfig,

    /// Last backup times for each interval
    last_backups: RwLock<Vec<Option<SystemTime>>>,
}

impl ShellHistory {
    /// Create a new ShellHistory, loading from the specified log file if it exists
    pub fn new(log_path: impl AsRef<Path>) -> io::Result<Self> {
        let log_path = log_path.as_ref().to_path_buf();
        let backup_config = BackupConfig::default();
        let last_backups = RwLock::new(vec![None; backup_config.intervals.len()]);

        let history = ShellHistory {
            entries: RwLock::new(HashMap::new()),
            entry_order: RwLock::new(Vec::new()),
            log_path,
            write_lock: Mutex::new(()),
            matcher: SkimMatcherV2::default(),
            backup_config,
            last_backups,
        };

        // Load existing history if the file exists
        if history.log_path.exists() {
            history.load_log()?;
        }

        Ok(history)
    }

    /// Create a new ShellHistory with custom backup configuration
    pub fn with_backup_config(
        log_path: impl AsRef<Path>,
        backup_config: BackupConfig,
    ) -> io::Result<Self> {
        let log_path = log_path.as_ref().to_path_buf();
        let last_backups = RwLock::new(vec![None; backup_config.intervals.len()]);

        let history = ShellHistory {
            entries: RwLock::new(HashMap::new()),
            entry_order: RwLock::new(Vec::new()),
            log_path,
            write_lock: Mutex::new(()),
            matcher: SkimMatcherV2::default(),
            backup_config,
            last_backups,
        };

        if history.log_path.exists() {
            history.load_log()?;
        }

        Ok(history)
    }

    /// Load the log file and rebuild in-memory state
    fn load_log(&self) -> io::Result<()> {
        let file = File::open(&self.log_path)?;
        let reader = BufReader::new(file);

        let mut entries = self.entries.write().unwrap();
        let mut entry_order = self.entry_order.write().unwrap();

        for line in reader.lines() {
            let line = line?;
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }

            // Skip lines that don't look like JSON objects
            if !trimmed.starts_with('{') {
                eprintln!(
                    "Warning: skipping non-JSON history line: {}",
                    if trimmed.len() > 50 {
                        &trimmed[..50]
                    } else {
                        trimmed
                    }
                );
                continue;
            }

            match serde_json::from_str::<LogEvent>(&line) {
                Ok(event) => self.apply_event(&mut entries, &mut entry_order, event),
                Err(e) => {
                    // Log parse errors but continue - we don't want to lose history
                    // due to a single corrupt line
                    eprintln!("Warning: failed to parse history line: {}", e);
                }
            }
        }

        Ok(())
    }

    /// Apply a log event to the in-memory state
    fn apply_event(
        &self,
        entries: &mut HashMap<EntryId, HistoryEntry>,
        entry_order: &mut Vec<EntryId>,
        event: LogEvent,
    ) {
        match event {
            LogEvent::Exec {
                id,
                cmd,
                timestamp,
                source,
                cwd,
            } => {
                let entry_id = EntryId::from_string(id);
                let entry = HistoryEntry {
                    id: entry_id.clone(),
                    command: cmd,
                    executed_at: UNIX_EPOCH + Duration::from_secs(timestamp),
                    exit_code: None,
                    source,
                    killed: false,
                    duration_ms: None,
                    cwd,
                };
                entries.insert(entry_id.clone(), entry);
                entry_order.push(entry_id);
            }
            LogEvent::Amend {
                id,
                exit_code,
                duration_ms,
                killed,
            } => {
                let entry_id = EntryId::from_string(id);
                if let Some(entry) = entries.get_mut(&entry_id) {
                    if let Some(code) = exit_code {
                        entry.exit_code = Some(code);
                    }
                    if let Some(dur) = duration_ms {
                        entry.duration_ms = Some(dur);
                    }
                    if let Some(k) = killed {
                        entry.killed = k;
                    }
                }
            }
            LogEvent::Import {
                id, cmd, timestamp, ..
            } => {
                let entry_id = EntryId::from_string(id);
                let entry = HistoryEntry {
                    id: entry_id.clone(),
                    command: cmd,
                    executed_at: UNIX_EPOCH + Duration::from_secs(timestamp),
                    exit_code: None,
                    source: CommandSource::Human,
                    killed: false,
                    duration_ms: None,
                    cwd: None,
                };
                entries.insert(entry_id.clone(), entry);
                entry_order.push(entry_id);
            }
        }
    }

    /// Write an event to the log file with fsync for durability
    fn write_event(&self, event: &LogEvent) -> io::Result<()> {
        let _lock = self.write_lock.lock().unwrap();

        // Ensure parent directory exists
        if let Some(parent) = self.log_path.parent() {
            fs::create_dir_all(parent)?;
        }

        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.log_path)?;

        // Use file locking for safe concurrent access across processes
        file.lock_exclusive()?;

        let mut line = serde_json::to_string(event)?;
        line.push('\n');
        file.write_all(line.as_bytes())?;
        file.sync_all()?;

        file.unlock()?;

        Ok(())
    }

    /// Record a new command execution
    ///
    /// This immediately writes to the log and fsyncs before returning,
    /// ensuring the command is never lost even if the shell crashes.
    ///
    /// Returns the EntryId which can be used to amend the entry later.
    pub fn record_command(&self, command: String, source: CommandSource) -> io::Result<EntryId> {
        self.record_command_with_cwd(command, source, None)
    }

    /// Record a new command execution with working directory
    pub fn record_command_with_cwd(
        &self,
        command: String,
        source: CommandSource,
        cwd: Option<String>,
    ) -> io::Result<EntryId> {
        let entry = HistoryEntry {
            id: EntryId::new(),
            command: command.clone(),
            executed_at: SystemTime::now(),
            exit_code: None,
            source,
            killed: false,
            duration_ms: None,
            cwd: cwd.clone(),
        };

        let timestamp = entry
            .executed_at
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        let event = LogEvent::Exec {
            id: entry.id.0.clone(),
            cmd: command,
            timestamp,
            source,
            cwd,
        };

        // Write to disk first (crash-safe)
        self.write_event(&event)?;

        // Then update in-memory state
        let entry_id = entry.id.clone();
        {
            let mut entries = self.entries.write().unwrap();
            let mut order = self.entry_order.write().unwrap();
            entries.insert(entry_id.clone(), entry);
            order.push(entry_id.clone());
        }

        // Check if we need to create a backup
        self.maybe_backup()?;

        Ok(entry_id)
    }

    /// Amend an existing history entry with completion information
    pub fn amend_entry(
        &self,
        id: &EntryId,
        exit_code: Option<i32>,
        duration_ms: Option<u64>,
        killed: Option<bool>,
    ) -> io::Result<()> {
        let event = LogEvent::Amend {
            id: id.0.clone(),
            exit_code,
            duration_ms,
            killed,
        };

        // Write to disk first
        self.write_event(&event)?;

        // Then update in-memory state
        let mut entries = self.entries.write().unwrap();
        if let Some(entry) = entries.get_mut(id) {
            if let Some(code) = exit_code {
                entry.exit_code = Some(code);
            }
            if let Some(dur) = duration_ms {
                entry.duration_ms = Some(dur);
            }
            if let Some(k) = killed {
                entry.killed = k;
            }
        }

        Ok(())
    }

    /// Mark a command as killed (e.g., by Ctrl+C)
    pub fn mark_killed(&self, id: &EntryId) -> io::Result<()> {
        self.amend_entry(id, None, None, Some(true))
    }

    /// Record the exit code of a command
    pub fn record_exit(&self, id: &EntryId, exit_code: i32, duration_ms: u64) -> io::Result<()> {
        self.amend_entry(id, Some(exit_code), Some(duration_ms), Some(false))
    }

    /// Get the total number of history entries
    pub fn len(&self) -> usize {
        self.entries.read().unwrap().len()
    }

    /// Check if history is empty
    pub fn is_empty(&self) -> bool {
        self.entries.read().unwrap().is_empty()
    }

    /// Get a specific entry by ID
    pub fn get(&self, id: &EntryId) -> Option<HistoryEntry> {
        self.entries.read().unwrap().get(id).cloned()
    }

    /// Get the most recent N entries
    pub fn recent(&self, n: usize) -> Vec<HistoryEntry> {
        let entries = self.entries.read().unwrap();
        let order = self.entry_order.read().unwrap();

        order
            .iter()
            .rev()
            .take(n)
            .filter_map(|id| entries.get(id).cloned())
            .collect()
    }

    /// Get all entries in chronological order
    pub fn all_entries(&self) -> Vec<HistoryEntry> {
        let entries = self.entries.read().unwrap();
        let order = self.entry_order.read().unwrap();

        order
            .iter()
            .filter_map(|id| entries.get(id).cloned())
            .collect()
    }

    /// Fuzzy search through history
    ///
    /// Returns matching entries sorted by match score (best matches first)
    pub fn search(&self, query: &str) -> Vec<SearchResult> {
        let entries = self.entries.read().unwrap();
        let order = self.entry_order.read().unwrap();

        let mut results: Vec<SearchResult> = order
            .iter()
            .filter_map(|id| {
                let entry = entries.get(id)?;
                let score = self.matcher.fuzzy_match(&entry.command, query)?;
                Some(SearchResult {
                    entry: entry.clone(),
                    score,
                })
            })
            .collect();

        // Sort by score descending
        results.sort_by(|a, b| b.score.cmp(&a.score));

        results
    }

    /// Search with a maximum number of results
    pub fn search_limit(&self, query: &str, limit: usize) -> Vec<SearchResult> {
        let mut results = self.search(query);
        results.truncate(limit);
        results
    }

    /// Search for exact prefix matches (useful for tab completion)
    pub fn search_prefix(&self, prefix: &str) -> Vec<HistoryEntry> {
        let entries = self.entries.read().unwrap();
        let order = self.entry_order.read().unwrap();

        order
            .iter()
            .rev()
            .filter_map(|id| {
                let entry = entries.get(id)?;
                if entry.command.starts_with(prefix) {
                    Some(entry.clone())
                } else {
                    None
                }
            })
            .collect()
    }

    /// Search history with match indices for highlighting.
    ///
    /// This method performs fuzzy search and returns results with:
    /// - Match indices for highlighting matched characters
    /// - Enhanced scoring that combines multiple factors:
    ///   - **Frequency bonus** (most important): Commands run many times score higher
    ///   - **Match score**: Quality of the fuzzy match (normalized)
    ///   - **Exit code bonus**: Successful commands (exit_code = 0) score higher
    ///   - **Recency bonus**: More recently executed commands score higher
    ///
    /// Results are deduplicated by command text, keeping the most recent entry
    /// for each unique command (which also has the best recency).
    ///
    /// If query is empty, returns most recent unique commands.
    pub fn search_with_indices(&self, query: &str, limit: usize) -> Vec<HistorySearchResult> {
        let entries = self.entries.read().unwrap();
        let order = self.entry_order.read().unwrap();

        // Scoring weights:
        // - Frequency is most important (commands you run often are likely what you want)
        // - Match quality + density together determine how well the query fits
        // - Recency is a tiebreaker (prefer recently used commands)
        // - Exit code is a minor bonus (success is nice but shouldn't override match quality)
        const MAX_FREQUENCY_BONUS: i64 = 100; // Dominates other factors
        const MAX_MATCH_SCORE: i64 = 50; // Fuzzy match quality
        const MAX_DENSITY_BONUS: i64 = 40; // Reward concentrated matches (query_len / cmd_len)
        const MAX_RECENCY_BONUS: i64 = 20; // Mild recency preference
        const MAX_EXIT_CODE_BONUS: i64 = 10; // Minor tiebreaker for successful commands

        let query_len = query.chars().count();

        // Pre-compute command statistics: (execution_count, most_recent_index, had_success)
        struct CommandStats {
            count: usize,
            most_recent_idx: usize,
            had_success: bool,
        }
        let mut command_stats: HashMap<&str, CommandStats> = HashMap::new();
        let mut max_count: usize = 1;

        for (idx, id) in order.iter().enumerate() {
            if let Some(entry) = entries.get(id) {
                let stats = command_stats.entry(&entry.command).or_insert(CommandStats {
                    count: 0,
                    most_recent_idx: idx,
                    had_success: false,
                });
                stats.count += 1;
                stats.most_recent_idx = idx; // Last one wins (order is chronological)
                if entry.exit_code == Some(0) {
                    stats.had_success = true;
                }
                max_count = max_count.max(stats.count);
            }
        }

        let total_entries = order.len();

        if query.is_empty() {
            // Return most recent unique commands when query is empty
            // Still apply scoring for frequency and exit code
            let mut seen_commands = std::collections::HashSet::new();
            let mut results = Vec::new();
            for id in order.iter().rev() {
                if let Some(entry) = entries.get(id) {
                    if seen_commands.insert(entry.command.clone()) {
                        let stats = command_stats.get(entry.command.as_str());
                        let mut breakdown = ScoreBreakdown::default();

                        if let Some(stats) = stats {
                            // Frequency bonus (log scale to avoid extreme dominance)
                            let freq_factor =
                                (stats.count as f64).ln_1p() / (max_count as f64).ln_1p();
                            breakdown.frequency_bonus =
                                (freq_factor * MAX_FREQUENCY_BONUS as f64) as i64;

                            // Exit code bonus
                            if stats.had_success {
                                breakdown.exit_code_bonus = MAX_EXIT_CODE_BONUS;
                            }
                        }

                        let score = breakdown.total();
                        results.push(HistorySearchResult {
                            entry: entry.clone(),
                            score,
                            score_breakdown: breakdown,
                            match_indices: Vec::new(),
                        });
                        if results.len() >= limit {
                            break;
                        }
                    }
                }
            }
            return results;
        }

        // Find the max fuzzy score for normalization
        let mut max_fuzzy_score: i64 = 1;
        let matches: Vec<_> = order
            .iter()
            .filter_map(|id| {
                let entry = entries.get(id)?;
                let (score, indices) = self.matcher.fuzzy_indices(&entry.command, query)?;
                Some((id, entry, score, indices))
            })
            .collect();

        for (_, _, score, _) in &matches {
            max_fuzzy_score = max_fuzzy_score.max(*score);
        }

        // Build results with composite scoring
        let mut results: Vec<HistorySearchResult> = matches
            .into_iter()
            .filter_map(|(_, entry, fuzzy_score, indices)| {
                let stats = command_stats.get(entry.command.as_str())?;

                let mut breakdown = ScoreBreakdown::default();

                // Match score (normalized to MAX_MATCH_SCORE)
                let match_factor = fuzzy_score as f64 / max_fuzzy_score as f64;
                breakdown.match_score = (match_factor * MAX_MATCH_SCORE as f64) as i64;

                // Density bonus: query_len / command_len
                // A 7-char query matching a 10-char command = 0.7 density (high)
                // A 7-char query matching a 100-char command = 0.07 density (low)
                let cmd_len = entry.command.chars().count().max(1);
                let density = query_len as f64 / cmd_len as f64;
                // Clamp to 1.0 (in case query is longer than command, though unlikely)
                let density = density.min(1.0);
                breakdown.density_bonus = (density * MAX_DENSITY_BONUS as f64) as i64;

                // Frequency bonus (log scale to smooth out extreme counts)
                let freq_factor = (stats.count as f64).ln_1p() / (max_count as f64).ln_1p();
                breakdown.frequency_bonus = (freq_factor * MAX_FREQUENCY_BONUS as f64) as i64;

                // Exit code bonus (if this command ever succeeded)
                if stats.had_success {
                    breakdown.exit_code_bonus = MAX_EXIT_CODE_BONUS;
                }

                // Recency bonus (based on most recent execution of this command)
                if total_entries > 1 {
                    let recency_factor = stats.most_recent_idx as f64 / (total_entries - 1) as f64;
                    breakdown.recency_bonus = (recency_factor * MAX_RECENCY_BONUS as f64) as i64;
                }

                let score = breakdown.total();
                Some(HistorySearchResult {
                    entry: entry.clone(),
                    score,
                    score_breakdown: breakdown,
                    match_indices: indices,
                })
            })
            .collect();

        // Sort by score descending
        results.sort_by(|a, b| b.score.cmp(&a.score));

        // Deduplicate by command text, keeping highest-scoring entry for each command
        let mut seen_commands = std::collections::HashSet::new();
        results.retain(|result| seen_commands.insert(result.entry.command.clone()));

        // Truncate to limit
        results.truncate(limit);

        results
    }

    /// Import from a .zsh_history file
    ///
    /// Format: `: timestamp:0;command` or just `command` for older formats
    pub fn import_zsh_history(&self, path: impl AsRef<Path>) -> io::Result<usize> {
        let file = File::open(path)?;
        let reader = BufReader::new(file);
        let mut count = 0;

        for line in reader.lines() {
            let line = line?;
            let (timestamp, command) = parse_zsh_history_line(&line);

            if command.is_empty() {
                continue;
            }

            // Check for duplicates
            {
                let entries = self.entries.read().unwrap();
                if entries.values().any(|e| e.command == command) {
                    continue;
                }
            }

            let id = EntryId::new();
            let event = LogEvent::Import {
                id: id.0.clone(),
                cmd: command.clone(),
                timestamp,
                original_format: Some("zsh".to_string()),
            };

            self.write_event(&event)?;

            let entry = HistoryEntry {
                id: id.clone(),
                command,
                executed_at: UNIX_EPOCH + Duration::from_secs(timestamp),
                exit_code: None,
                source: CommandSource::Human,
                killed: false,
                duration_ms: None,
                cwd: None,
            };

            let mut entries = self.entries.write().unwrap();
            let mut order = self.entry_order.write().unwrap();
            entries.insert(id.clone(), entry);
            order.push(id);

            count += 1;
        }

        Ok(count)
    }

    /// Import from a .bash_history file
    ///
    /// Format: One command per line, or with timestamps if HISTTIMEFORMAT is set
    pub fn import_bash_history(&self, path: impl AsRef<Path>) -> io::Result<usize> {
        let file = File::open(path)?;
        let reader = BufReader::new(file);
        let mut count = 0;
        let mut pending_timestamp: Option<u64> = None;

        for line in reader.lines() {
            let line = line?;

            // Check for timestamp line (format: #1234567890)
            if line.starts_with('#') {
                if let Ok(ts) = line[1..].trim().parse::<u64>() {
                    pending_timestamp = Some(ts);
                    continue;
                }
            }

            let command = line.trim().to_string();
            if command.is_empty() || command.starts_with('#') {
                continue;
            }

            // Check for duplicates
            {
                let entries = self.entries.read().unwrap();
                if entries.values().any(|e| e.command == command) {
                    pending_timestamp = None;
                    continue;
                }
            }

            let timestamp = pending_timestamp.unwrap_or_else(|| {
                SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs()
            });
            pending_timestamp = None;

            let id = EntryId::new();
            let event = LogEvent::Import {
                id: id.0.clone(),
                cmd: command.clone(),
                timestamp,
                original_format: Some("bash".to_string()),
            };

            self.write_event(&event)?;

            let entry = HistoryEntry {
                id: id.clone(),
                command,
                executed_at: UNIX_EPOCH + Duration::from_secs(timestamp),
                exit_code: None,
                source: CommandSource::Human,
                killed: false,
                duration_ms: None,
                cwd: None,
            };

            let mut entries = self.entries.write().unwrap();
            let mut order = self.entry_order.write().unwrap();
            entries.insert(id.clone(), entry);
            order.push(id);

            count += 1;
        }

        Ok(count)
    }

    /// Check if a backup is needed and create one if so
    fn maybe_backup(&self) -> io::Result<()> {
        let now = SystemTime::now();
        let mut last_backups = self.last_backups.write().unwrap();

        for (i, interval) in self.backup_config.intervals.iter().enumerate() {
            let needs_backup = match last_backups[i] {
                None => true,
                Some(last) => now.duration_since(last).unwrap_or_default() >= *interval,
            };

            if needs_backup {
                self.create_backup(i)?;
                last_backups[i] = Some(now);
            }
        }

        Ok(())
    }

    /// Create a backup at the specified interval index
    fn create_backup(&self, interval_index: usize) -> io::Result<()> {
        if !self.log_path.exists() {
            return Ok(());
        }

        let backup_name = format!(
            "{}.backup.{}",
            self.log_path.file_name().unwrap().to_string_lossy(),
            interval_index
        );
        let backup_path = self.log_path.parent().unwrap().join(backup_name);

        fs::copy(&self.log_path, &backup_path)?;

        Ok(())
    }

    /// Force a backup at all intervals (useful before shutdown)
    pub fn force_backup(&self) -> io::Result<()> {
        for i in 0..self.backup_config.intervals.len() {
            self.create_backup(i)?;
        }
        Ok(())
    }

    /// Get the path to the log file
    pub fn log_path(&self) -> &Path {
        &self.log_path
    }

    /// Compact the log file by rewriting it with only the current state
    ///
    /// This removes redundant amend entries and reduces file size.
    /// Call this periodically (e.g., on shell startup) if the log gets large.
    pub fn compact(&self) -> io::Result<()> {
        let _lock = self.write_lock.lock().unwrap();

        // Create backup before compacting
        self.force_backup()?;

        let entries = self.entries.read().unwrap();
        let order = self.entry_order.read().unwrap();

        // Write to a temp file first
        let temp_path = self.log_path.with_extension("log.tmp");
        {
            let mut file = OpenOptions::new()
                .create(true)
                .write(true)
                .truncate(true)
                .open(&temp_path)?;

            for id in order.iter() {
                if let Some(entry) = entries.get(id) {
                    // Write as a single exec event with all data
                    let timestamp = entry
                        .executed_at
                        .duration_since(UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_secs();

                    let exec_event = LogEvent::Exec {
                        id: entry.id.0.clone(),
                        cmd: entry.command.clone(),
                        timestamp,
                        source: entry.source,
                        cwd: entry.cwd.clone(),
                    };

                    let mut line = serde_json::to_string(&exec_event)?;
                    line.push('\n');
                    file.write_all(line.as_bytes())?;

                    // Write amend if there's completion data
                    if entry.exit_code.is_some() || entry.duration_ms.is_some() || entry.killed {
                        let amend_event = LogEvent::Amend {
                            id: entry.id.0.clone(),
                            exit_code: entry.exit_code,
                            duration_ms: entry.duration_ms,
                            killed: if entry.killed { Some(true) } else { None },
                        };
                        let mut line = serde_json::to_string(&amend_event)?;
                        line.push('\n');
                        file.write_all(line.as_bytes())?;
                    }
                }
            }

            file.sync_all()?;
        }

        // Atomically replace the old file
        fs::rename(&temp_path, &self.log_path)?;

        Ok(())
    }
}

/// Parse a zsh_history line
///
/// Format: `: timestamp:0;command` or just `command`
fn parse_zsh_history_line(line: &str) -> (u64, String) {
    // Extended format: `: 1234567890:0;command`
    if line.starts_with(": ") {
        if let Some(semi_pos) = line.find(';') {
            let meta = &line[2..semi_pos];
            let command = line[semi_pos + 1..].to_string();

            // Parse timestamp from "timestamp:0" format
            if let Some(colon_pos) = meta.find(':') {
                if let Ok(ts) = meta[..colon_pos].parse::<u64>() {
                    return (ts, command);
                }
            }
        }
    }

    // Simple format: just the command
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    (now, line.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_record_and_retrieve() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        let history = ShellHistory::new(&log_path).unwrap();

        let id = history
            .record_command("ls -la".to_string(), CommandSource::Human)
            .unwrap();

        let entry = history.get(&id).unwrap();
        assert_eq!(entry.command, "ls -la");
        assert_eq!(entry.source, CommandSource::Human);
        assert!(entry.exit_code.is_none());

        // Amend with exit code
        history.record_exit(&id, 0, 150).unwrap();

        let entry = history.get(&id).unwrap();
        assert_eq!(entry.exit_code, Some(0));
        assert_eq!(entry.duration_ms, Some(150));
    }

    #[test]
    fn test_persistence() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        // Create and populate history
        {
            let history = ShellHistory::new(&log_path).unwrap();
            history
                .record_command("echo hello".to_string(), CommandSource::Human)
                .unwrap();
            history
                .record_command("cargo build".to_string(), CommandSource::Ai)
                .unwrap();
        }

        // Reload and verify
        {
            let history = ShellHistory::new(&log_path).unwrap();
            assert_eq!(history.len(), 2);

            let recent = history.recent(10);
            assert_eq!(recent[0].command, "cargo build");
            assert_eq!(recent[0].source, CommandSource::Ai);
            assert_eq!(recent[1].command, "echo hello");
        }
    }

    #[test]
    fn test_fuzzy_search() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        let history = ShellHistory::new(&log_path).unwrap();
        history
            .record_command("git commit -m 'test'".to_string(), CommandSource::Human)
            .unwrap();
        history
            .record_command("git push origin main".to_string(), CommandSource::Human)
            .unwrap();
        history
            .record_command("cargo test".to_string(), CommandSource::Human)
            .unwrap();

        let results = history.search("git");
        assert_eq!(results.len(), 2);

        let results = history.search("carg");
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].entry.command, "cargo test");
    }

    #[test]
    fn test_parse_zsh_history() {
        let (ts, cmd) = parse_zsh_history_line(": 1704067200:0;echo hello");
        assert_eq!(ts, 1704067200);
        assert_eq!(cmd, "echo hello");

        let (_, cmd) = parse_zsh_history_line("simple command");
        assert_eq!(cmd, "simple command");
    }

    #[test]
    fn test_mark_killed() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        let history = ShellHistory::new(&log_path).unwrap();
        let id = history
            .record_command("sleep 100".to_string(), CommandSource::Human)
            .unwrap();

        history.mark_killed(&id).unwrap();

        let entry = history.get(&id).unwrap();
        assert!(entry.killed);
    }

    #[test]
    fn test_search_with_indices() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        let history = ShellHistory::new(&log_path).unwrap();

        // Record some commands with different properties
        let id1 = history
            .record_command("git commit -m 'test'".to_string(), CommandSource::Human)
            .unwrap();
        history.record_exit(&id1, 0, 100).unwrap(); // Successful

        let _id2 = history
            .record_command("git push origin main".to_string(), CommandSource::Ai)
            .unwrap();
        // No exit recorded (still running or crashed)

        let id3 = history
            .record_command("git status".to_string(), CommandSource::Human)
            .unwrap();
        history.record_exit(&id3, 0, 50).unwrap(); // Successful

        // Search for "git"
        let results = history.search_with_indices("git", 10);
        assert_eq!(results.len(), 3);

        // Check that match indices are provided
        assert!(!results[0].match_indices.is_empty());

        // All results should have 'g', 'i', 't' matched at positions 0, 1, 2
        for result in &results {
            assert!(result.match_indices.contains(&0)); // 'g'
            assert!(result.match_indices.contains(&1)); // 'i'
            assert!(result.match_indices.contains(&2)); // 't'
        }

        // Empty query should return most recent commands
        let empty_results = history.search_with_indices("", 10);
        assert_eq!(empty_results.len(), 3);
        // Most recent should be first (git status was last recorded)
        assert_eq!(empty_results[0].entry.command, "git status");
    }

    #[test]
    fn test_search_frequency_ranking() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        let history = ShellHistory::new(&log_path).unwrap();

        // Record "git status" 5 times (frequently used command)
        for _ in 0..5 {
            let id = history
                .record_command("git status".to_string(), CommandSource::Human)
                .unwrap();
            history.record_exit(&id, 0, 50).unwrap();
        }

        // Record "git stash" once (less frequently used)
        let id = history
            .record_command("git stash".to_string(), CommandSource::Human)
            .unwrap();
        history.record_exit(&id, 0, 50).unwrap();

        // Search for "git st" - both match, but "git status" should rank higher due to frequency
        let results = history.search_with_indices("git st", 10);
        assert_eq!(results.len(), 2);

        // "git status" should be first due to higher frequency
        assert_eq!(results[0].entry.command, "git status");
        assert_eq!(results[1].entry.command, "git stash");

        // Verify frequency bonus is reflected in score breakdown
        assert!(
            results[0].score_breakdown.frequency_bonus > results[1].score_breakdown.frequency_bonus
        );
    }

    #[test]
    fn test_search_score_breakdown() {
        let dir = tempdir().unwrap();
        let log_path = dir.path().join("history.log");

        let history = ShellHistory::new(&log_path).unwrap();

        // Record a command that succeeded
        let id = history
            .record_command("cargo build".to_string(), CommandSource::Human)
            .unwrap();
        history.record_exit(&id, 0, 100).unwrap();

        // Record a command that failed
        let id = history
            .record_command("cargo bild".to_string(), CommandSource::Human)
            .unwrap();
        history.record_exit(&id, 1, 50).unwrap();

        let results = history.search_with_indices("cargo b", 10);
        assert_eq!(results.len(), 2);

        // Find the successful command
        let successful = results
            .iter()
            .find(|r| r.entry.command == "cargo build")
            .unwrap();
        let failed = results
            .iter()
            .find(|r| r.entry.command == "cargo bild")
            .unwrap();

        // Successful command should have exit code bonus
        assert!(successful.score_breakdown.exit_code_bonus > 0);
        assert_eq!(failed.score_breakdown.exit_code_bonus, 0);

        // Both should have non-zero match scores
        assert!(successful.score_breakdown.match_score > 0);
        assert!(failed.score_breakdown.match_score > 0);

        // Total should equal sum of components
        assert_eq!(successful.score, successful.score_breakdown.total());
        assert_eq!(failed.score, failed.score_breakdown.total());
    }
}

/// Default implementation for backward compatibility
impl Default for ShellHistory {
    fn default() -> Self {
        // Use a default path in the user's home directory
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
        let log_path = PathBuf::from(home).join(".shell_history.log");

        ShellHistory::new(log_path).expect("Failed to create default ShellHistory")
    }
}
